<?php
/** Include file for classes.
* Classes must be saved at include/classes directory, then included here.
* Don't remove the dependency classes section, or else your application will broke somehow.
* Only change a dependency class if your know what you're doing.
* Add your classes in the section application classes
*/
include("iniset.inc");

//////////////////////////////////////////////////////////////////
/** Dependency Classes  
*   The classes included below are vital for the fLamework functionalities.
*   Be careful when changing something here and in theses files.
*/
include_once('class.userInfo.php');

/////////////////////////////////////////////////////////////////
/** Application classes
*   Include here the classes for your applications.
*   Before including a new classe, please check if nothing will overlap the fLamework classes.
*/

?>
